### ISSUE TITLE
No testing rules?

### ISSUE THREAD

**Issue by rijkvanzanten** [Mimaaa/backend-package-assigment#3]
You have installed `mocha`, and have a `npm run test` in place, but no actual testing rules setup?

**Comment by Mimaaa** [comment]
Thought Mocha had some default options. Should have read the manual. :taco:

**Comment by rijkvanzanten** [comment]
So you added rules / fixed it?

Closing issues without resolutions? <3

**Comment by Mimaaa** [comment]
I chose to remove the package, because I should read the docs first to get a good grasp of writing the rules when my schedule permits me to.

**Comment by rijkvanzanten** [comment]
Gotcha! Small tip for next time, reference the issue in the commit where you solve it. That way, it shows up on the issue page 😄 

https://help.github.com/articles/closing-issues-using-keywords/
